package git

import (
	"bytes"
	"sort"
	"strings"
)

// ParsePorcelainStatus parses the raw output of `git status --porcelain=v1 -uall`.
func ParsePorcelainStatus(output string) *StatusResult {
	result := &StatusResult{
		StagedFiles:    make([]FileStatus, 0),
		UnstagedFiles:  make([]FileStatus, 0),
		UntrackedFiles: make([]string, 0),
		UnmergedFiles:  make([]string, 0),
	}

	lines := strings.Split(output, "\n")
	for _, line := range lines {
		line = strings.TrimRight(line, "\r")
		if len(line) < 3 {
			continue
		}

		x := line[0]
		y := line[1]
		rawPath := line[3:]

		// Handle unmerged / merge conflict states
		if isUnmerged(x, y) {
			p := cleanPath(rawPath)
			if p != "" {
				result.UnmergedFiles = append(result.UnmergedFiles, p)
			}
			continue
		}

		// Handle untracked files
		if x == '?' && y == '?' {
			p := cleanPath(rawPath)
			if p != "" {
				result.UntrackedFiles = append(result.UntrackedFiles, p)
			}
			continue
		}

		// Handle ignored files
		if x == '!' && y == '!' {
			continue
		}

		// Handle staged changes (index)
		if x != ' ' && x != '?' {
			var origPath, newPath string
			if x == 'R' || x == 'C' {
				origPath, newPath = parseRenamePath(rawPath)
			} else {
				origPath = ""
				newPath = cleanPath(rawPath)
			}
			result.StagedFiles = append(result.StagedFiles, FileStatus{
				Path:           newPath,
				OrigPath:       origPath,
				StagingStatus:  StatusCode(string(x)),
				WorkTreeStatus: StatusCode(string(y)),
			})
		}

		// Handle unstaged changes (worktree)
		if y != ' ' && y != '?' {
			var origPath, newPath string
			if (x == 'R' || x == 'C') || (y == 'R' || y == 'C') {
				origPath, newPath = parseRenamePath(rawPath)
			} else {
				origPath = ""
				newPath = cleanPath(rawPath)
			}
			result.UnstagedFiles = append(result.UnstagedFiles, FileStatus{
				Path:           newPath,
				OrigPath:       origPath,
				StagingStatus:  StatusCode(string(x)),
				WorkTreeStatus: StatusCode(string(y)),
			})
		}
	}

	result.IsClean = len(result.StagedFiles) == 0 &&
		len(result.UnstagedFiles) == 0 &&
		len(result.UntrackedFiles) == 0 &&
		len(result.UnmergedFiles) == 0

	return result
}

// isUnmerged returns true if the status pair represents a merge conflict.
func isUnmerged(x, y byte) bool {
	// Standard git unmerged combinations: DD, AU, UD, UA, DU, AA, UU
	if x == 'U' || y == 'U' {
		return true
	}
	if x == 'A' && y == 'A' {
		return true
	}
	if x == 'D' && y == 'D' {
		return true
	}
	return false
}

// parseRenamePath splits a rename/copy path string ("old_path -> new_path") into individual paths.
// If the source path is quoted, it matches the unescaped closing quote followed by " -> ".
func parseRenamePath(raw string) (origPath, newPath string) {
	if strings.HasPrefix(raw, "\"") {
		for i := 1; i < len(raw); i++ {
			if raw[i] == '\\' {
				i++
				continue
			}
			if raw[i] == '"' {
				rest := raw[i+1:]
				if strings.HasPrefix(rest, " -> ") {
					orig := cleanPath(raw[:i+1])
					dest := cleanPath(rest[4:])
					return orig, dest
				}
				return "", cleanPath(raw)
			}
		}
		return "", cleanPath(raw)
	}

	if idx := strings.Index(raw, " -> "); idx != -1 {
		orig := cleanPath(raw[:idx])
		dest := cleanPath(raw[idx+4:])
		return orig, dest
	}
	return "", cleanPath(raw)
}

// cleanPath unquotes and normalizes a file path using forward slashes.
func cleanPath(p string) string {
	if p == "" {
		return ""
	}
	p = unescapeGitPath(p)
	if p == "" {
		return ""
	}
	p = strings.TrimPrefix(p, "./")
	return p
}

// unescapeGitPath unescapes C-style quoted strings and octal escape sequences generated by Git into raw bytes.
func unescapeGitPath(p string) string {
	if len(p) < 2 || p[0] != '"' || p[len(p)-1] != '"' {
		return p
	}
	var buf bytes.Buffer
	s := p[1 : len(p)-1]
	for i := 0; i < len(s); i++ {
		if s[i] == '\\' && i+1 < len(s) {
			i++
			switch s[i] {
			case 'a':
				buf.WriteByte('\a')
			case 'b':
				buf.WriteByte('\b')
			case 'f':
				buf.WriteByte('\f')
			case 'n':
				buf.WriteByte('\n')
			case 'r':
				buf.WriteByte('\r')
			case 't':
				buf.WriteByte('\t')
			case 'v':
				buf.WriteByte('\v')
			case '\\':
				buf.WriteByte('\\')
			case '"':
				buf.WriteByte('"')
			case '0', '1', '2', '3', '4', '5', '6', '7':
				val := int(s[i] - '0')
				digits := 1
				for digits < 3 && i+1 < len(s) && s[i+1] >= '0' && s[i+1] <= '7' {
					i++
					val = val*8 + int(s[i]-'0')
					digits++
				}
				buf.WriteByte(byte(val))
			default:
				buf.WriteByte(s[i])
			}
		} else {
			buf.WriteByte(s[i])
		}
	}
	return buf.String()
}

// ExtractModifiedFiles extracts all unique modified, staged, unstaged, untracked, and unmerged file paths.
func ExtractModifiedFiles(status *StatusResult) []string {
	if status == nil {
		return []string{}
	}

	seen := make(map[string]struct{})

	addPath := func(p string) {
		if p != "" {
			seen[p] = struct{}{}
		}
	}

	for _, f := range status.StagedFiles {
		addPath(f.Path)
		addPath(f.OrigPath)
	}

	for _, f := range status.UnstagedFiles {
		addPath(f.Path)
		addPath(f.OrigPath)
	}

	for _, p := range status.UntrackedFiles {
		addPath(p)
	}

	for _, p := range status.UnmergedFiles {
		addPath(p)
	}

	result := make([]string, 0, len(seen))
	for p := range seen {
		result = append(result, p)
	}

	sort.Strings(result)
	return result
}

// ParseNameOnlyList parses output from `git diff --name-only` into normalized paths.
func ParseNameOnlyList(output string) []string {
	lines := strings.Split(output, "\n")
	seen := make(map[string]struct{})
	result := make([]string, 0)

	for _, line := range lines {
		p := cleanPath(line)
		if p != "" {
			if _, exists := seen[p]; !exists {
				seen[p] = struct{}{}
				result = append(result, p)
			}
		}
	}

	sort.Strings(result)
	return result
}

// ParseDiffNameStatus parses output from `git diff --name-status` into FileChange structs.
func ParseDiffNameStatus(output string) []FileChange {
	lines := strings.Split(output, "\n")
	changes := make([]FileChange, 0)

	for _, line := range lines {
		line = strings.TrimRight(line, "\r\n")
		if strings.TrimSpace(line) == "" {
			continue
		}

		parts := strings.Split(line, "\t")
		if len(parts) < 2 {
			continue
		}

		statusCode := StatusCode(strings.TrimSpace(parts[0]))
		if len(statusCode) > 1 && (statusCode[0] == 'R' || statusCode[0] == 'C') {
			statusCode = StatusCode(string(statusCode[0]))
		}

		if len(parts) >= 3 && (statusCode == StatusRenamed || statusCode == StatusCopied) {
			origPath := cleanPath(parts[1])
			newPath := cleanPath(parts[2])
			changes = append(changes, FileChange{
				Path:     newPath,
				OrigPath: origPath,
				Status:   statusCode,
			})
		} else {
			path := cleanPath(parts[1])
			changes = append(changes, FileChange{
				Path:   path,
				Status: statusCode,
			})
		}
	}

	return changes
}
